### PR TITLE
[mod] allow rules with only strop and without action or subrule

### PR DESCRIPTION
**Pull request by dalf**

### CODE REVIEW

**Comment by dalf** [comment]
@MrPaulBlack I've merged this PR, so you can remove this line https://github.com/paulgoio/searxng/blob/ae9de21edc6c09518998c1b26c37de5fe43185f8/src/rules.json#L86

**Comment by mrpaulblack** [comment]
Thank you! I have the PR deployed at: https://staging.paulgo.io I am currently still getting rate limited and I have no clue why; Here is my rules.json ( https://github.com/paulgoio/searxng/blob/main/src/rules.json ); I think it has something to do with the block filters being global (meaning that they share the counter), but I am not sure and cannot figure it out tbh...

**Comment by dalf** [comment]
Perhaps this:
https://github.com/paulgoio/searxng/blob/226cfa11369cd2a2397fc30a98c1fc04f55b3c37/src/rules.json#L190-L199

On FF: `Accept: image/avif,image/webp,*/*`
On Chrome: `Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`

**Comment by mrpaulblack** [comment]
> On FF: Accept: image/avif,image/webp,*/*

I actually do not think that is the problem since it late limits pictures and everything else after around  30 burst requests... So its probably:
```json
    {
        "name": "useragent limit, all paths",
        "interval": 30,
        "limit": 200,
        "aggregations": ["Header:X-Forwarded-For", "Header:User-Agent"],
        "stop": true,
        "actions": [
            {"name": "block",
             "params": {"message": "Rate limit exceeded, try again later."}}
        ]
    }
```

But this should not get triggered because the `/image_proxy` rules before all have an stop action...

**Pull request merged**
